/**
 * Shared CLI setup — graph loading and store creation.
 *
 * Single source of truth for the layout of `.freelance/`, memory and
 * traversal-state path resolution, and config-to-runtime wiring.
 */

import fs from "node:fs";
import path from "node:path";
import type { Runtime } from "../compose.js";
import { buildMemoryStore, composeRuntime } from "../compose.js";
import type { FreelanceConfig } from "../config.js";
import { loadConfigFromDirs } from "../config.js";
import { resolveContextCaps } from "../engine/context.js";
import { loadGraphsGraceful, resolveGraphsDirs, resolveSourceRoot } from "../graph-resolution.js";
import type { MemoryConfig, MemoryStore } from "../memory/index.js";
import { extractSection } from "../section-resolver.js";
import type { SourceOptions } from "../sources.js";
import type { TraversalStore } from "../state/index.js";
import type { ValidatedGraph } from "../types.js";

// --- Layout helpers ---
//
// `.freelance/` contains everything: source artifacts (config.yml,
// config.local.yml, *.workflow.yaml) alongside runtime artifacts
// (memory/memory.db, traversals/*.json). Source vs generated
// distinction is maintained via the generated .gitignore.

/** Path to the traversals JSON-file store under a graphs directory. */
export function traversalsDirFor(graphsDir: string): string {
  return path.join(graphsDir, "traversals");
}

/** Path to the memory directory containing memory.db + WAL/SHM sidecars. */
export function memoryDirFor(graphsDir: string): string {
  return path.join(graphsDir, "memory");
}

/** Default path to the memory database file inside a graphs directory. */
export function memoryDbPathFor(graphsDir: string): string {
  return path.join(memoryDirFor(graphsDir), "memory.db");
}

const GITIGNORE_MARKER = "# Generated by Freelance";
const GITIGNORE_CONTENT = `${GITIGNORE_MARKER} — do not edit
memory/
traversals/
config.local.yml
`;

// Upsert only files we generated. Pre-1.3 installs have a stale
// marker-bearing file ignoring `.state/` instead of `memory/` +
// `traversals/`, so runtime artifacts land untracked unless we
// rewrite. User-authored files (no marker) are left alone.
function ensureGitignore(graphsDir: string): void {
  const ignorePath = path.join(graphsDir, ".gitignore");
  try {
    if (fs.existsSync(ignorePath)) {
      const existing = fs.readFileSync(ignorePath, "utf-8");
      if (!existing.startsWith(GITIGNORE_MARKER)) return;
      if (existing === GITIGNORE_CONTENT) return;
    }
    fs.writeFileSync(ignorePath, GITIGNORE_CONTENT);
  } catch {
    // Best-effort — graphsDir may be read-only (e.g. plugin cache)
  }
}

/**
 * Ensure a `.freelance/` directory is ready for runtime writes. The
 * directory itself is expected to exist already (it's where workflow
 * yaml files live); this helper just drops in the generated
 * `.gitignore` on first use. Returns the directory path for chaining.
 */
export function ensureFreelanceDir(graphsDir: string): string {
  ensureGitignore(graphsDir);
  return graphsDir;
}

/**
 * Resolve the traversals JSON-store directory. Picks the first
 * existing graphsDir from the list, falling back to the first entry
 * if none exist yet. `openStateStore` creates the directory if
 * missing, so callers don't need to mkdir first.
 */
export function resolveTraversalsDir(graphsDirs: string[]): string {
  for (const dir of graphsDirs) {
    if (fs.existsSync(dir)) return traversalsDirFor(dir);
  }
  return traversalsDirFor(graphsDirs[0] ?? ".freelance");
}

// --- Memory config resolution ---

function ensureMemoryDir(dir: string): string {
  const resolved = path.resolve(dir);
  if (!fs.existsSync(resolved)) {
    fs.mkdirSync(resolved, { recursive: true });
  }
  return path.join(resolved, "memory.db");
}

/**
 * Resolve the effective memory configuration from (a) CLI flags, (b)
 * a pre-loaded or freshly-loaded FreelanceConfig, and (c) the default
 * location under the first graphs directory.
 *
 * Precedence:
 *   - `opts.memory === false` (CLI `--no-memory`) → memory off
 *   - config `memory.enabled === false` AND `opts.memory !== true` → off
 *   - otherwise on, with db path from (CLI `--memory-dir` > config `memory.dir` > default)
 *
 * The default is `<graphsDir>/memory/memory.db`, under the first
 * existing graphs directory. The `memory/` subdir is created lazily.
 */
export function resolveMemoryConfig(
  graphsDirs: string[],
  opts: { memoryDir?: string; memory?: boolean },
  config?: FreelanceConfig,
): MemoryConfig | null {
  if (opts.memory === false) return null;

  const cfg = config ?? loadConfigFromDirs(graphsDirs);

  if (cfg.memory.enabled === false && opts.memory !== true) return null;

  let dbPath: string;
  if (opts.memoryDir) {
    dbPath = ensureMemoryDir(opts.memoryDir);
  } else if (cfg.memory.dir) {
    dbPath = ensureMemoryDir(cfg.memory.dir);
  } else {
    const graphsDir = graphsDirs[0] ?? ".freelance";
    dbPath = ensureMemoryDir(memoryDirFor(graphsDir));
  }

  return {
    enabled: true,
    db: dbPath,
  };
}

// --- CLI setup helpers ---

interface CliSetupOptions {
  workflows?: string | string[];
  maxDepth?: number;
  sourceRoot?: string;
}

interface CliSetup {
  graphs: Map<string, ValidatedGraph>;
  graphsDirs: string[];
  sourceRoot: string | undefined;
  sourceOpts: SourceOptions;
}

/** Load graphs and resolve directories for CLI commands. */
export function loadGraphSetup(opts: CliSetupOptions): CliSetup {
  const graphsDirs = resolveGraphsDirs(opts.workflows);
  const { graphs } = loadGraphsGraceful(graphsDirs);
  const sourceRoot = resolveSourceRoot(graphsDirs, opts.sourceRoot);
  const sectionResolver = (filePath: string, section: string) => extractSection(filePath, section);
  return {
    graphs,
    graphsDirs,
    sourceRoot,
    sourceOpts: { resolver: sectionResolver, basePath: sourceRoot },
  };
}

/**
 * Build a CLI-facing runtime via `composeRuntime` — hook wiring,
 * memory-store lifecycle, and state backend construction all flow
 * through the shared composition root.
 */
export function createTraversalStore(opts: CliSetupOptions): {
  store: TraversalStore;
  setup: CliSetup;
  runtime: Runtime;
} {
  const setup = loadGraphSetup(opts);
  const graphsDir = setup.graphsDirs[0] ?? ".freelance";
  ensureFreelanceDir(graphsDir);
  const traversalsDir = resolveTraversalsDir(setup.graphsDirs);
  const fileConfig = loadConfigFromDirs(setup.graphsDirs);
  const memConfig = resolveMemoryConfig(setup.graphsDirs, {}, fileConfig);

  const runtime = composeRuntime({
    graphsDir,
    graphs: setup.graphs,
    stateDir: traversalsDir,
    sourceRoot: setup.sourceRoot,
    sectionResolver: (filePath, section) => extractSection(filePath, section),
    memory: memConfig,
    maxDepth: opts.maxDepth ?? fileConfig.maxDepth ?? 5,
    hookTimeoutMs: fileConfig.hooks.timeoutMs,
    contextCaps: resolveContextCaps(fileConfig.context),
  });

  return { store: runtime.store, setup, runtime };
}

/** Create a MemoryStore for CLI memory commands. */
export function createMemoryStore(opts: CliSetupOptions): { store: MemoryStore; setup: CliSetup } {
  const setup = loadGraphSetup(opts);
  const config = loadConfigFromDirs(setup.graphsDirs);
  const memConfig = resolveMemoryConfig(setup.graphsDirs, {}, config);
  if (!memConfig) {
    throw new Error("Memory is disabled. Enable it in config.yml or remove --no-memory.");
  }
  if (!setup.sourceRoot) {
    throw new Error(
      "createMemoryStore: sourceRoot could not be resolved from graphsDirs. " +
        "Pass --workflows explicitly or configure workflows in config.yml.",
    );
  }
  const store = buildMemoryStore(memConfig, setup.sourceRoot);
  return { store, setup };
}
