/**
 * Shared CLI setup — graph loading and store creation.
 *
 * Single source of truth for state directory resolution, DB paths,
 * and memory config parsing. Used by both CLI commands and the MCP
 * entry point in index.ts.
 */

import path from "node:path";
import fs from "node:fs";
import { TraversalStore } from "../state/index.js";
import { openStateDatabase } from "../state/index.js";
import { MemoryStore } from "../memory/index.js";
import { resolveGraphsDirs, resolveSourceRoot, loadGraphsGraceful } from "../graph-resolution.js";
import { loadConfigFromDirs } from "../config.js";
import type { FreelanceConfig } from "../config.js";
import { extractSection } from "../section-resolver.js";
import type { ValidatedGraph } from "../types.js";
import type { SourceOptions } from "../sources.js";
import type { MemoryConfig } from "../memory/index.js";

// --- State directory resolution ---

function stateDir(graphsDir: string): string {
  return path.join(graphsDir, ".state");
}

/** Content for .freelance/.gitignore — covers all generated artifacts. */
const GITIGNORE_CONTENT = `# Generated by Freelance — do not edit
.state/
config.local.yml
`;

/**
 * Ensure .freelance/.gitignore exists so generated artifacts
 * (state DBs, memory DBs, local config) are excluded from version control.
 */
function ensureGitignore(graphsDir: string): void {
  const ignorePath = path.join(graphsDir, ".gitignore");
  if (fs.existsSync(ignorePath)) return;
  try {
    fs.writeFileSync(ignorePath, GITIGNORE_CONTENT);
  } catch {
    // Best-effort — graphsDir may be read-only (e.g. plugin cache)
  }
}

export function ensureStateDir(graphsDir: string): string {
  const dir = stateDir(graphsDir);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  ensureGitignore(graphsDir);
  return dir;
}

/**
 * Resolve the state DB path without creating directories.
 * Use ensureStateDir() before opening the DB for writes.
 */
export function resolveStateDb(graphsDirs: string[]): string {
  for (const dir of graphsDirs) {
    if (fs.existsSync(dir)) {
      return path.join(stateDir(dir), "state.db");
    }
  }
  return path.join(stateDir(graphsDirs[0] ?? ".freelance"), "state.db");
}

// --- Memory config resolution ---

function ensureMemoryDir(dir: string): string {
  const resolved = path.resolve(dir);
  if (!fs.existsSync(resolved)) {
    fs.mkdirSync(resolved, { recursive: true });
  }
  return path.join(resolved, "memory.db");
}

export function resolveMemoryConfig(
  graphsDirs: string[],
  opts: { memoryDir?: string; memory?: boolean },
  config?: FreelanceConfig,
): MemoryConfig | null {
  if (opts.memory === false) return null;

  const cfg = config ?? loadConfigFromDirs(graphsDirs);

  if (cfg.memory.enabled === false && opts.memory !== true) return null;

  // Precedence: CLI flag > config file > default (.state/memory.db)
  let dbPath: string;
  if (opts.memoryDir) {
    dbPath = ensureMemoryDir(opts.memoryDir);
  } else if (cfg.memory.dir) {
    dbPath = ensureMemoryDir(cfg.memory.dir);
  } else {
    dbPath = path.join(ensureStateDir(graphsDirs[0] ?? ".freelance"), "memory.db");
  }

  return {
    enabled: true,
    db: dbPath,
    ignore: cfg.memory.ignore,
    collections: cfg.memory.collections,
  };
}

// --- CLI setup helpers ---

export interface CliSetupOptions {
  workflows?: string | string[];
  maxDepth?: number;
  sourceRoot?: string;
}

export interface CliSetup {
  graphs: Map<string, ValidatedGraph>;
  graphsDirs: string[];
  sourceRoot: string | undefined;
  sourceOpts: SourceOptions;
}

/** Load graphs and resolve directories for CLI commands. */
export function loadGraphSetup(opts: CliSetupOptions): CliSetup {
  const graphsDirs = resolveGraphsDirs(opts.workflows);
  const { graphs } = loadGraphsGraceful(graphsDirs);
  const sourceRoot = resolveSourceRoot(graphsDirs, opts.sourceRoot);
  const sectionResolver = (filePath: string, section: string) => extractSection(filePath, section);
  return {
    graphs,
    graphsDirs,
    sourceRoot,
    sourceOpts: { resolver: sectionResolver, basePath: sourceRoot },
  };
}

/** Create a TraversalStore for CLI traversal commands. */
export function createTraversalStore(opts: CliSetupOptions): { store: TraversalStore; setup: CliSetup } {
  const setup = loadGraphSetup(opts);
  ensureStateDir(setup.graphsDirs[0] ?? ".freelance");
  const stateDb = resolveStateDb(setup.graphsDirs);
  const db = openStateDatabase(stateDb);
  const maxDepth = opts.maxDepth ?? 5;
  const store = new TraversalStore(db, setup.graphs, { maxDepth });
  return { store, setup };
}

/** Create a MemoryStore for CLI memory commands. */
export function createMemoryStore(opts: CliSetupOptions): { store: MemoryStore; setup: CliSetup } {
  const setup = loadGraphSetup(opts);
  const config = loadConfigFromDirs(setup.graphsDirs);
  const memConfig = resolveMemoryConfig(setup.graphsDirs, {}, config);
  if (!memConfig) {
    throw new Error("Memory is disabled. Enable it in config.yml or remove --no-memory.");
  }
  const store = new MemoryStore(memConfig.db, setup.sourceRoot, memConfig.ignore, memConfig.collections);
  return { store, setup };
}
