/**
 * Shared CLI setup — graph loading and store creation.
 *
 * Single source of truth for the layout of `.freelance/`, memory and
 * traversal-state path resolution, and config-to-runtime wiring.
 */

import fs from "node:fs";
import path from "node:path";
import type { Runtime } from "../compose.js";
import { buildMemoryStore, composeRuntime } from "../compose.js";
import type { FreelanceConfig } from "../config.js";
import { loadConfigFromDirs } from "../config.js";
import { resolveContextCaps } from "../engine/context.js";
import { EC } from "../error-codes.js";
import { EngineError } from "../errors.js";
import { loadGraphsGraceful, resolveGraphsDirs, resolveSourceRoot } from "../graph-resolution.js";
import type { MemoryConfig, MemoryStore } from "../memory/index.js";
import { extractSection } from "../section-resolver.js";
import type { SourceOptions } from "../sources.js";
import type { TraversalStore } from "../state/index.js";
import type { LoadError, ValidatedGraph } from "../types.js";

// --- Layout helpers ---
//
// `.freelance/` contains everything: source artifacts (config.yml,
// config.local.yml, *.workflow.yaml) alongside runtime artifacts
// (memory/memory.db, traversals/*.json). Source vs generated
// distinction is maintained via the generated .gitignore.

/** Path to the traversals JSON-file store under a graphs directory. */
export function traversalsDirFor(graphsDir: string): string {
  return path.join(graphsDir, "traversals");
}

/** Path to the memory directory containing memory.db + WAL/SHM sidecars. */
export function memoryDirFor(graphsDir: string): string {
  return path.join(graphsDir, "memory");
}

/** Default path to the memory database file inside a graphs directory. */
export function memoryDbPathFor(graphsDir: string): string {
  return path.join(memoryDirFor(graphsDir), "memory.db");
}

const GENERATED_MARKER = "# Generated by Freelance";

const GITIGNORE_CONTENT = `${GENERATED_MARKER} — do not edit
memory/
traversals/
config.local.yml
`;

// Pin EOL on every generated file in `.freelance/` so committed
// content survives Windows clones with `core.autocrlf=true`. Without
// this, autocrlf rewrites the working-tree copy of `.gitignore` (and
// anything else generated as LF) to CRLF on checkout while the index
// stays LF, producing a phantom diff that blocks workspace-cleanliness
// gates in tooling that wraps Freelance.
const GITATTRIBUTES_CONTENT = `${GENERATED_MARKER} — do not edit
* eol=lf
`;

// Upsert only files we generated. Pre-1.3 installs have a stale
// marker-bearing file ignoring `.state/` instead of `memory/` +
// `traversals/`, so runtime artifacts land untracked unless we
// rewrite. User-authored files (no marker) are left alone.
function upsertGenerated(filePath: string, content: string): void {
  try {
    if (fs.existsSync(filePath)) {
      const existing = fs.readFileSync(filePath, "utf-8");
      if (!existing.startsWith(GENERATED_MARKER)) return;
      if (existing === content) return;
    }
    fs.writeFileSync(filePath, content);
  } catch {
    // Best-effort — graphsDir may be read-only (e.g. plugin cache)
  }
}

/**
 * Ensure a `.freelance/` directory is ready for runtime writes. The
 * directory itself is expected to exist already (it's where workflow
 * yaml files live); this helper drops in the generated `.gitignore`
 * and `.gitattributes` on first use. Returns the directory path for
 * chaining.
 */
export function ensureFreelanceDir(graphsDir: string): string {
  upsertGenerated(path.join(graphsDir, ".gitignore"), GITIGNORE_CONTENT);
  upsertGenerated(path.join(graphsDir, ".gitattributes"), GITATTRIBUTES_CONTENT);
  return graphsDir;
}

/**
 * Resolve the traversals JSON-store directory. Picks the first
 * existing graphsDir from the list, falling back to the first entry
 * if none exist yet. `openStateStore` creates the directory if
 * missing, so callers don't need to mkdir first.
 */
export function resolveTraversalsDir(graphsDirs: string[]): string {
  for (const dir of graphsDirs) {
    if (fs.existsSync(dir)) return traversalsDirFor(dir);
  }
  return traversalsDirFor(graphsDirs[0] ?? ".freelance");
}

// --- Memory config resolution ---

/**
 * Resolve the effective memory configuration from (a) CLI flags, (b)
 * a pre-loaded or freshly-loaded FreelanceConfig, and (c) the default
 * location under the first graphs directory.
 *
 * Pure — no filesystem writes. See `docs/decisions.md` § "Memory
 * directory creation lives in `buildMemoryStore`".
 *
 * Precedence:
 *   - `opts.memory === false` (CLI `--no-memory`) → memory off
 *   - config `memory.enabled === false` AND `opts.memory !== true` → off
 *   - otherwise on, with db path from (CLI `--memory-dir` > config `memory.dir` > default)
 *
 * The default is `<graphsDir>/memory/memory.db`, under the first
 * graphs directory.
 */
export function resolveMemoryConfig(
  graphsDirs: string[],
  opts: { memoryDir?: string; memory?: boolean },
  config?: FreelanceConfig,
): MemoryConfig | null {
  if (opts.memory === false) return null;

  const cfg = config ?? loadConfigFromDirs(graphsDirs);

  if (cfg.memory.enabled === false && opts.memory !== true) return null;

  const dir = opts.memoryDir ?? cfg.memory.dir ?? memoryDirFor(graphsDirs[0] ?? ".freelance");

  return {
    enabled: true,
    db: path.join(path.resolve(dir), "memory.db"),
  };
}

// --- CLI setup helpers ---

interface CliSetupOptions {
  workflows?: string | string[];
  maxDepth?: number;
  sourceRoot?: string;
}

/**
 * Memory verbs operate on a flat namespace with no graph-id coupling,
 * so workflow yaml parsing is unnecessary work for every `freelance
 * memory <verb>` invocation. `MemorySetup` is the lean half of
 * `CliSetup` — same path resolution + config, minus the graph parse.
 */
export interface MemorySetup {
  graphsDirs: string[];
  sourceRoot: string | undefined;
  config: FreelanceConfig;
}

interface CliSetup extends MemorySetup {
  graphs: Map<string, ValidatedGraph>;
  sourceOpts: SourceOptions;
  /** Non-fatal per-file load failures from graphsDirs; empty when all files parsed + validated. */
  loadErrors: readonly LoadError[];
}

/** Resolve dirs, sourceRoot, and config without parsing any workflow yaml. */
export function loadMemorySetup(opts: CliSetupOptions): MemorySetup {
  const graphsDirs = resolveGraphsDirs(opts.workflows);
  const sourceRoot = resolveSourceRoot(graphsDirs, opts.sourceRoot);
  const config = loadConfigFromDirs(graphsDirs);
  return { graphsDirs, sourceRoot, config };
}

/** Load graphs and resolve directories for CLI commands. */
export function loadGraphSetup(opts: CliSetupOptions): CliSetup {
  const base = loadMemorySetup(opts);
  const { graphs, errors: loadErrors } = loadGraphsGraceful(base.graphsDirs);
  return {
    ...base,
    graphs,
    sourceOpts: { resolver: extractSection, basePath: base.sourceRoot },
    loadErrors,
  };
}

/**
 * Build a CLI-facing runtime via `composeRuntime` — hook wiring,
 * memory-store lifecycle, and state backend construction all flow
 * through the shared composition root.
 */
export function createTraversalStore(opts: CliSetupOptions): {
  store: TraversalStore;
  setup: CliSetup;
  runtime: Runtime;
} {
  const setup = loadGraphSetup(opts);
  const graphsDir = setup.graphsDirs[0] ?? ".freelance";
  ensureFreelanceDir(graphsDir);
  const traversalsDir = resolveTraversalsDir(setup.graphsDirs);
  const memConfig = resolveMemoryConfig(setup.graphsDirs, {}, setup.config);

  const runtime = composeRuntime({
    graphsDir,
    graphs: setup.graphs,
    stateDir: traversalsDir,
    sourceRoot: setup.sourceRoot,
    sectionResolver: extractSection,
    memory: memConfig,
    maxDepth: opts.maxDepth ?? setup.config.maxDepth ?? 5,
    hookTimeoutMs: setup.config.hooks.timeoutMs,
    contextCaps: resolveContextCaps(setup.config.context),
    loadErrors: setup.loadErrors,
  });

  return { store: runtime.store, setup, runtime };
}

/** Create a MemoryStore for CLI memory commands. */
export function createMemoryStore(opts: CliSetupOptions): {
  store: MemoryStore;
  setup: MemorySetup;
} {
  const setup = loadMemorySetup(opts);
  const memConfig = resolveMemoryConfig(setup.graphsDirs, {}, setup.config);
  if (!memConfig) {
    throw new EngineError(
      "Memory is disabled. Enable it in config.yml or remove --no-memory.",
      EC.MEMORY_DISABLED,
    );
  }
  if (!setup.sourceRoot) {
    throw new EngineError(
      "createMemoryStore: sourceRoot could not be resolved from graphsDirs. " +
        "Pass --workflows explicitly or configure workflows in config.yml.",
      EC.MEMORY_UNRESOLVED_SOURCE_ROOT,
    );
  }
  const store = buildMemoryStore(memConfig, setup.sourceRoot);
  return { store, setup };
}
