# freelance fish completion
complete -c freelance -n "__fish_use_subcommand" -a init -d "Set up Freelance"
complete -c freelance -n "__fish_use_subcommand" -a validate -d "Validate graph definitions"
complete -c freelance -n "__fish_use_subcommand" -a visualize -d "Export graph diagram"
complete -c freelance -n "__fish_use_subcommand" -a mcp -d "Start MCP server"
complete -c freelance -n "__fish_use_subcommand" -a daemon -d "Manage daemon"
complete -c freelance -n "__fish_use_subcommand" -a status -d "Show graphs and active traversals"
complete -c freelance -n "__fish_use_subcommand" -a start -d "Start a new traversal"
complete -c freelance -n "__fish_use_subcommand" -a advance -d "Take an edge to the next node"
complete -c freelance -n "__fish_use_subcommand" -a context -d "Update session context"
complete -c freelance -n "__fish_use_subcommand" -a inspect -d "Inspect current graph state"
complete -c freelance -n "__fish_use_subcommand" -a reset -d "Clear a traversal"
complete -c freelance -n "__fish_use_subcommand" -a memory -d "Knowledge graph"
complete -c freelance -n "__fish_use_subcommand" -a guide -d "Authoring guide"
complete -c freelance -n "__fish_use_subcommand" -a distill -d "Distill source into propositions"
complete -c freelance -n "__fish_use_subcommand" -a sources -d "Manage source bindings"
complete -c freelance -n "__fish_use_subcommand" -a memory-register -d "Register a source file"
complete -c freelance -n "__fish_use_subcommand" -a completion -d "Shell completion"
complete -c freelance -n "__fish_use_subcommand" -l json -d "Output as JSON"
complete -c freelance -n "__fish_use_subcommand" -l no-color -d "Disable colors"
complete -c freelance -n "__fish_use_subcommand" -l verbose -d "Verbose output"
complete -c freelance -n "__fish_use_subcommand" -s q -l quiet -d "Quiet mode"
complete -c freelance -n "__fish_seen_subcommand_from daemon" -a "start stop status"
complete -c freelance -n "__fish_seen_subcommand_from memory" -a "status browse inspect search related by-source register emit end"
complete -c freelance -n "__fish_seen_subcommand_from context" -a "set"
complete -c freelance -n "__fish_seen_subcommand_from sources" -a "hash check validate"
complete -c freelance -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
