# freelance fish completion
complete -c freelance -n "__fish_use_subcommand" -a init -d "Set up Freelance"
complete -c freelance -n "__fish_use_subcommand" -a validate -d "Validate graph definitions"
complete -c freelance -n "__fish_use_subcommand" -a visualize -d "Export graph diagram"
complete -c freelance -n "__fish_use_subcommand" -a mcp -d "Start MCP server"
complete -c freelance -n "__fish_use_subcommand" -a daemon -d "Manage daemon"
complete -c freelance -n "__fish_use_subcommand" -a traversals -d "Manage traversals"
complete -c freelance -n "__fish_use_subcommand" -a completion -d "Shell completion"
complete -c freelance -n "__fish_use_subcommand" -l json -d "Output as JSON"
complete -c freelance -n "__fish_use_subcommand" -l no-color -d "Disable colors"
complete -c freelance -n "__fish_use_subcommand" -l verbose -d "Verbose output"
complete -c freelance -n "__fish_use_subcommand" -s q -l quiet -d "Quiet mode"
complete -c freelance -n "__fish_seen_subcommand_from daemon" -a "start stop status"
complete -c freelance -n "__fish_seen_subcommand_from traversals" -a "list inspect reset"
complete -c freelance -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
